"""Single FastMCP instance shared by all tool modules."""

from mcp.server.fastmcp import FastMCP

from backend.agent.hard_rules import AGENT_HARD_RULES

mcp = FastMCP(
    "uefn-ducky",
    instructions=(
        "UEFN Ducky — MCP server for UEFN (Unreal Editor for Fortnite) plus Store desktop "
        "plugins (e.g. blender_*). Desktop-plugin tools do NOT need the UEFN listener.\n\n"
        f"{AGENT_HARD_RULES}\n"
        "**Plans (HARD):** Multi-step diagnose/fix/build (≥2 tool rounds) MUST use "
        "`ducky_create_plan` with a followable `nodes` tree (Diagnose → Fix → Verify; "
        "each leaf = one action + Done-when). Never substitute a chat prose Fix plan. "
        "Execute depth-first: `ducky_plan_update_node` in_progress→completed. If the "
        "approach changes, update the tree before more mutators — never thrash off-plan. "
        "Plan mode: create/update then stop.\n\n"
        "**FIRST — Verse errors / code / game logic (host tools ONLY):** "
        "`workspace_list_verse_errors` → `workspace_list_dir` / `workspace_read_file` → "
        "`workspace_write_file` → `workspace_list_verse_errors` again. Never wait for the "
        "listener. On a fix-errors turn do NOT call `ping`, `get_project_info`, "
        "`ducky_get_errors`, `execute_python`, or any listener/editor tool — those are not "
        "Verse diagnostics. If a listener tool does not return immediately it is offline/"
        "broken: do not retry; stay on `workspace_*`. "
        "`workspace_compile_verse` only after Problems is clean AND UEFN is known open.\n\n"
        "**Blender (Store plugin):** when blender tools are enabled and the Blender MCP "
        "socket is up, call blender_* immediately — never wait for UEFN / the Fortnite "
        "listener. Teach Connect only when blender_status reports disconnected.\n\n"
        "**Store plugins:** enabled plugins may register extra tools on this same MCP "
        "server (e.g. discord_*, blender_*). If those tools are listed, call them — do "
        "not claim the integration is unavailable.\n\n"
        "**File / code edits (listener OFFLINE OK):** changing Verse behavior or game logic → "
        "`workspace_list_dir` → `workspace_read_file` → `workspace_write_file` on `Verse/**/*.verse`, "
        "then `workspace_list_verse_errors`. Never wait for the listener or ask for device labels "
        "before reading project Verse files.\n\n"
        "**Verse digests (disk READ ONLY — UEFN auto-edits them):** never guess API names; "
        "never hand-edit digests. **UEFN rewrites `*.digest.verse` on Verse build.** "
        "After creating assets or Verse that should appear in digests: "
        "`workspace_compile_verse` (UEFN open) → then look inside with "
        "`list_verse_digests` / `search_verse_digest` → `get_verse_api(name)` / "
        "`list_verse_types` (Fortnite / Verse / UnrealEngine / Assets). "
        "Content Browser weapon/item assets → `search_assets`.\n\n"
        "**Level / wiring (listener required):** placing Verse classes/devices into the level or "
        "connecting `@editable` refs in Details → call `uefn_skill` once for the exact procedure.\n\n"
        "**Tool choice (in order)**\n"
        "1. Host / panel tools for Verse files and diagnostics — `workspace_*`, digests, "
        "`ducky_*` (status only when asked; never for compile errors).\n"
        "2. Structured thin MCP editor tools — **one editor operation per call** "
        "(spawn_actor, wire_verse_device_ref, set_verse_editable, …) when the listener is online.\n"
        "3. `listener_command` — single-op listener commands only (see ping.commands).\n"
        "4. `uefn_editor_python_hints` — reflection gotchas before `execute_python`.\n"
        "5. `execute_python` — last resort for full unreal API access (never for Verse errors).\n\n"
        "**NEVER:** batch_commands, bulk_*, setup_verse_device, spawn_actor_batch — removed. "
        "For N devices call spawn_actor N times; for N wires call wire_verse_device_ref N times; "
        "save_current_level once at the end.\n\n"
        "**CRITICAL — one editor command per assistant message:** never issue multiple "
        "wire_verse_device_ref / wire_verse_device_array / set_verse_editable / "
        "set_creative_device_fields / spawn_actor / set_actor_* / destroy/delete / "
        "instantiate_prefab / save_current_level / execute_python calls in parallel or in "
        "the same tool-call batch. Wait for each result before the next. Parallel calls "
        "freeze/crash UEFN. Prefer `spawn_actor(..., label=..., folder=...)` over "
        "separate label/folder calls.\n\n"
        "**SFX / horns / alarms:** place Fortnite Creative **Audio Player** devices only "
        "(`audio_player_device` in Verse). Never Speakers, prop meshes, or "
        "`spawn_actor(actor_class=\"audio_player_device\")` — search `/Game/Creative` → "
        "spawn `…_C`. Load `skill_read_subskill(\"uefn\", \"creative_devices\")`.\n\n"
        "**NEVER in execute_python:** os.walk / rglob over Fortnite install or "
        "UnrealEditorFortnite AppData, reading .uasset/.umap binaries, or scanning for "
        "`__verse_0x` hashes — that freezes the editor main thread. Use "
        "list_verse_property_hashes / get_verse_editables / workspace_* instead.\n\n"
        "Performance: use compact responses (pretty=false), pagination (offset/limit/fields) on "
        "get_all_actors, list_assets, and search_assets.\n\n"
        "**Scene inventory:** Verse devices and custom-labeled actors are NOT Fort* actors. "
        "Use find_devices(label_filter=…) or get_all_actors(label_filter=…) — never class_prefix='Fort'.\n\n"
        "**Device APIs:** verse_script (VerseDevice_C) → inspect_verse_device / wire_verse_device_ref / "
        "set_verse_editable. creative_device (granters, buttons) → inspect_creative_device / "
        "set_creative_device_fields.\n\n"
        "Workspace file tools use UEFN_VSCODE_WORKSPACE_FOLDERS. For tkinter via execute_python, "
        "use get_tk_root() and tk.Toplevel — never tk.Tk()."
    ),
)
