// The Appearance CSS variables plugin panels get (keys of computeCssVars), written as
// a Python module the plugin checker reads. Runs with generate-critical-css.ts on
// every dev start and build, so the list can't drift from the theme engine.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { defaultFoundation } from "../src/theme/defaultTokens.ts";
import { computeCssVars } from "../src/theme/tokenEngine.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "../../../backend/uefn_plugins/appearance_vars.py");
const names = Object.keys(computeCssVars({ foundation: defaultFoundation(), overrides: {}, statusOverrides: {} })).sort();
const content =
  '"""Appearance CSS variables every plugin panel gets (``var(--name)``): the keys of the\n' +
  "app's theme engine (computeCssVars in web/src/theme/tokenEngine.ts, from\n" +
  "defaultTokens.ts). Generated by web/scripts/generate-appearance-vars.ts on every dev\n" +
  "start and build; do not edit. test_appearance_vars.py fails when it drifts.\n" +
  '"""\n' +
  "\n" +
  "NAMES = frozenset(\n" +
  "    {\n" +
  names.map((name) => `        "${name}",\n`).join("") +
  "    }\n" +
  ")\n";
writeFileSync(out, content);
console.log(`Wrote appearance_vars.py (${names.length} variables)`);
