"""Always-on agent hard rules shared by MCP instructions, BYOA bootstrap, and chat prompts."""

AGENT_HARD_RULES = (
    "**Agent hard rules (first-try):**\n"
    "- **Prefer official UEFN MCP first (HARD):** When `ducky_get_status.epic_mcp_online` "
    "is true, ALWAYS use nested Epic `unreal__*` "
    "(`unreal__list_toolsets` → `unreal__describe_toolset` → `unreal__call_tool`) for "
    "anything Epic covers — Creative devices, Scene Graph entities, PIC/session, "
    "in-editor Verse build, actors/levels/assets, and Epic material/Niagara/UMG toolsets. "
    "Do NOT use the Ducky listener for those jobs when Epic can do them. "
    "Listener is fallback only for Epic-offline gaps + Ducky-only work "
    "(offline `workspace_*`, VerseDevice `@editable` wires, prefab helpers, screenshots/"
    "Meshy/Store plugins, `spawn_actor` for props Epic cannot place). "
    "Never fall back to pruned Ducky `find_devices` / `inspect_creative_device` / "
    "`set_creative_device_fields` / `play_in_editor` / `create_entity` / `list_entities` "
    "while Epic is online and responding. **Epic errors → degrade, don't stall:** "
    "`epic_mcp_online` is a TCP probe, not a session guarantee — if a nested "
    "`unreal__*` call errors or the tools are missing, retry ONCE, then use the "
    "closest Ducky listener tool for the rest of the turn and finish the task "
    "(note the degraded path in one line; suggest a uefn MCP reconnect only after "
    "the work is done — never stop mid-task to ask).\n"
    "- **Epic UEFN MCP (HARD):** Settings → MCPs → **UEFN MCP (Epic)** (`unreal-mcp`, "
    "`http://127.0.0.1:8000/mcp`). Nested under Ducky as **three** tools only: "
    "`unreal__list_toolsets` → `unreal__describe_toolset(toolset_name=…)` → "
    "`unreal__call_tool(toolset_name=…, tool_name=…, arguments={…})`. There are no flat "
    "`unreal__create_entity` / `unreal__find_devices` names — always go through toolsets. "
    "Key toolsets: `ValkyrieToolset.DeviceToolset`, `ValkyrieToolset.EntityToolset`, "
    "`ValkyrieToolset.VerseToolset`, `ValkyrieToolset.SessionToolset`, "
    "`EditorToolset.EditorAppToolset`, plus `editor_toolset.toolsets.*` (actors/assets/"
    "materials/Niagara/…). Details: `skill_read_subskill(\"uefn\", \"epic_mcp\")`. "
    "Check `ducky_get_status.epic_mcp_online`. If false and the task needs Epic, STOP — "
    "copy `epic_mcp_setup_steps` (enable the island in Ducky, open it in UEFN). "
    "If epic_mcp_online is true but `unreal__list_toolsets` is missing or errors, fall "
    "back to the Ducky equivalents for this turn and keep working — mention a uefn MCP "
    "reconnect at the END of the task; do not toggle Toolsets, do not stop mid-task. "
    "Ignore `listener_init_race` whenever `online` is true. "
    "Offline `workspace_*` file edits are still allowed. Epic toolsets speak **XYZ**; "
    "UEFN world is **LUF** — do not pass SpatialMath LUF into Epic `arguments`.\n"
    "- `search_assets` uses **`search=`** (not `query` / `name_filter`). Creative "
    "props/devices/prefab kits: `directory=\"/Game/Creative\"` (or BuildingActors / Sets / "
    "Devices subfolders) — **never** `/Fortnite` (UI gallery only). Small `limit`; paginate "
    "with `offset`/`limit`/`fields`. Catalog map: "
    '`skill_read_subskill("leveldesign", "content_catalog")`.\n'
    "- Verse `*_device` names are **API types** — never "
    '`spawn_actor(actor_class="teleporter_device")`. Place Creative devices via Epic '
    "`unreal__call_tool` → `ValkyrieToolset.DeviceToolset` (`PlaceDevice`, "
    "`GetDeviceProperties`, …). `spawn_actor(asset_path=\"…_C\")` remains for props/meshes. "
    "API: `search_verse_digest` / `get_verse_api`. Find types with "
    "`list_verse_types(kind=\"class\", name_filter=…)` or `search_verse_digest` — "
    "not unfiltered `list_verse_devices`.\n"
    "- Screenshots / snips: `take_high_res_screenshot` / chat snip → use returned "
    "``path`` under `%LOCALAPPDATA%/UEFN-Ducky/tool_captures/` only. Capture "
    "tools also return MCP image content / auto-attach vision. **Never** write "
    "captures into the UEFN project folder. Never Bash `find`/`ls` for PNGs.\n"
    "- **Project folder storage (HARD):** never create Ducky side-files inside "
    "the UEFN project except ``.ducky/**`` (tests, tasks). Caches, temps, "
    "captures, memory, diagnostics, plugin scratch → "
    "`%LOCALAPPDATA%/UEFN-Ducky/` or OS temp — **never** `Saved/DuckyCaptures`, "
    "`.uefn-ducky`, or other junk at project root. Game content the user asked "
    "for (`Content/Verse/**`, assets) is fine — **never** `.py` / `.pyc`.\n"
    "- **Research budget (HARD — write, don't re-verify):** code inside loaded "
    "skills/subskills/templates is pre-verified — NEVER re-check its APIs "
    "symbol-by-symbol in digests (no `get_verse_api(\"Distance\")` sweeps for names "
    "a skill already shows). Digest-lookup only names you are inventing that no "
    "loaded skill shows, plus whatever `workspace_list_verse_errors` flags AFTER "
    "you write — that error list is the verification gate, not pre-flight digest "
    "sweeps. Budget ~5 digest lookups and ~3 subskill loads per task, then WRITE "
    "the files. Skill cross-links (\"see also\" / \"Details:\") are optional "
    "deep-dives for when you are stuck — not prerequisites. **Two search misses → "
    "move on:** if a tool/API search returns nothing twice with sensible names, it "
    "does not exist — use the closest listed alternative or plain Verse; never "
    "grind name variants.\n"
    "- Windows shell: use `py -3`, never `python3`. Prefer MCP over shell.\n"
    "- Truncated MCP result → re-call with tighter args. Never Read/Grep "
    "`**/tool-results/**` or `**/agent-tools/**` dumps.\n"
    "- BEFORE Hub/level/device work: load matching skill (`uefn` / `islandsettings` / "
    "`leveldesign`). Prefer `skill_read_subskill` — never IDE-Read `~/.claude/skills` / "
    "`~/.cursor/skills` / `references/*.md`.\n"
    "- Organize as you place: pass `label` + `folder` on `spawn_actor` (same tick) — "
    "never leave devices/props at Outliner root. Prefer that over separate "
    "`set_actor_label` / `set_actor_folder` calls. Nested folders by area/system "
    "(e.g. `Hub/Spawners`, `Hub/Teleporters`, `Area1/Combat`).\n"
    "- **Never search the UEFN project root** (or `Saved/`, `Intermediate/`, "
    "`DerivedDataCache/`, `*.uasset` binaries). Scope host searches to "
    "`Content/Verse/**` (and other text under `Content/` you need). Unscoped "
    "greps over `.uasset` freeze the machine.\n"
    "- **Verse `@editable` is always yours to wire:** fields live on the Script "
    "object as mangled `__verse_0x<HASH>_<Field>` names — the plain Verse name "
    "never resolves. `get_verse_editables` STOP is advisory, not a verdict. "
    "Resolve (`list_verse_property_hashes(refresh=true)` / re-inspect / read the "
    "mangled name), then `wire_verse_*` / `set_verse_editable`, then verify. "
    "Never ask the user to Build Verse, paste a T3D export, or drag refs in Details. "
    "Do not re-issue the same failing wire in a loop.\n"
    "- **Editor busy:** if a tool says the editor is busy running another command — "
    "wait; do not re-issue or spam parallel editor tools.\n"
    "- **Verse folders:** NEVER dump new `.verse` at `Content/Verse/` root. One system "
    "per folder (`Verse/Economy/…`, `Verse/Shop/…`, `Verse/PlayerCore/…`). Prefer "
    "`verse_template_apply(id)` (creates the pack folder). Hand-write: "
    '`workspace_list_dir("Verse")` then `workspace_write_file("Verse/<System>/<file>.verse", …)` '
    "(parents auto-created). Only `module_declarations.verse` (+ tiny helpers) at Verse "
    'root. Details: `skill_read_subskill("verse", "modules")`.\n'
    "- **Project assets only:** `create_material` / `create_material_instance` / "
    "`create_niagara_system` / `create_widget_blueprint` / `create_data_table` / "
    "`create_folder` / `import_asset` / `duplicate_asset` / `rename_asset` / "
    "`meshy_import_to_uefn` / `gdrive_import_to_uefn` / `create_level_sequence` / "
    "`create_prefab_from_entities` / `create_empty_prefab` MUST use `get_project_info().content_root` "
    "(e.g. `/MyProject/Materials/...`). **Never invent `/Game/Materials`**, `/Game/VFX`, "
    "`/Game/UI`, `/Game/Data`, `/Game/Meshes`, `/Game/Meshy`, or `/Game/Retargeting` for "
    "new island assets — that causes unsaved packages and cook "
    "`Disallowed reference to /Game/...`. Omit `folder` / `destination_path` to let the "
    "listener pin the project mount. `/Game/Creative` is read/search only.\n"
    "- **Persistence `weak_map` (HARD):** never remove player keys once added "
    "(removing breaks saves). Replace values only via rebuild+`set`. Do not "
    "add/remove persistable fields without "
    '`skill_read_subskill("verse","persistence")` + `sys_persistence_migration` '
    "(carry-all helpers). Session maps ≠ persist maps.\n"
    "- **UEFN digests are READ-ONLY (HARD — NEVER mutate):** never write, edit, "
    "delete, rename, patch, or `workspace_write_file` any `*.digest.verse` "
    "(Fortnite / Verse / UnrealEngine / Assets). **UEFN auto-edits digests itself** "
    "on Verse build / import — you do not. Workflow: write project Verse under "
    "`Content/Verse/**` → when UEFN is open run `workspace_compile_verse` (Verse "
    "build) → then **look inside** digests with `list_verse_digests` / "
    "`search_verse_digest` / `get_verse_api` / `list_verse_types` (Assets digest "
    "especially after new materials/meshes/prefabs). Missing type? Build first, "
    "then re-search — never invent by patching a digest.\n"
    "- **Write boundary (HARD):** `workspace_write_file` (and `execute_python` / "
    "listener file I/O) may only write **`Content/**`** and **`.ducky/**`**. Never "
    "touch UEFN core files, `Saved/`, `Intermediate/`, `DerivedDataCache/`, or the "
    "project root. Scratch → `%LOCALAPPDATA%/UEFN-Ducky/` or OS temp.\n"
    "- **No Python in the island (HARD):** never create or write a `.py` / `.pyc` "
    "file anywhere inside a UEFN project — not extra files under `Content/Python/`, "
    "not the project root, not `.ducky/**`. The **only** allowed island `.py` is "
    "Ducky's managed `Content/Python/init_unreal.py` (listener boot). **Never "
    "delete it.** Extra `.py` files get Epic `[ContainsPythonData]` and block "
    "session launch. `execute_python` is in-memory only — never have it write a "
    "file to disk. Scratch → `%LOCALAPPDATA%/UEFN-Ducky/` or OS temp.\n"
    "- **Inspect is not a census (HARD):** Creative device census/edit is nested Epic "
    "`unreal__*` (not `find_devices` / `inspect_creative_device`). Never loop "
    "`inspect_verse_device` over the level — each call hits the UEFN game "
    "thread and freezes the editor. Inspect only the ONE Verse device you are about "
    "to write. Field names come from `workspace_read_file` of that class's `.verse`.\n"
    "- **Verse build lifecycle (HARD):** `workspace_compile_verse` returning "
    "`[WinError 10054]` means the Verse **build started** (UEFN tears down the "
    "bridge socket while compiling) — wait minutes, poll a read-only signal like "
    "`list_verse_types`, **never retry**. A regenerated digest does **not** mean "
    "the Verse VM relinked. Nested Epic entity component calls returning "
    "`class_path` under `/Engine/Transient` with `VERSE_DEAD_*` is a stale class — "
    "rebuild Verse, then destroy and recreate the entity. Digest deadlock (`Script error 9002: "
    "Unable to import resolve` cascading to `9000: previous link task did not "
    "complete successfully`): comment out the problem Verse → rebuild and wait → "
    "confirm the digest is fresh with `list_verse_types` → uncomment → rebuild. "
    "Never patch the digest. Details: "
    '`skill_read_subskill("uefn", "verse_build_lifecycle")`.\n'
    "- **You do the editor work (HARD):** never ask the user to click Details, "
    "Content Browser, Build Verse, drag `@editable` refs, create AnimPresets / "
    "NPCDefs / character Blueprints, assign a definition onto a spawner, or fill "
    "animation slots. Find the tool (`ducky_get_tools` / `skill_read_subskill`) and "
    "call it. Custom-mesh NPCs: `npc_author_capabilities` then "
    "`create_physics_asset_for_mesh` / `create_anim_preset` / "
    "`create_character_blueprint` / `create_npc_character_definition` / "
    "`set_npc_definition_behavior` / `set_npc_spawner_definition`. Reaction clips: "
    "`duplicate_asset` into the Verse module folder and reference those ids in "
    "Verse **you write** — not Details. Missing a tool name? `ducky_get_tools` / "
    "`ducky_find_tools` / `skill_read_subskill` — then call it. The only human "
    "asks left are things only they can do (restart UEFN, import a pack they own, "
    "Epic MCP setup when `epic_mcp_online` is false).\n"
    "- **Write the game, don't paste it (HARD):** the user describes *what* they "
    "want. You load the matching skill, discover tools, and **author original "
    "Verse + assets for this island**. Do not dump a 700-line example for them to "
    "copy. Do not wait for a paste-this-prompt blob. Do not "
    '`verse_template_apply("npc_ecosystem")` unless they asked for that exact '
    "cat+dog pack. NPC systems: "
    '`verse_template_apply("npc_core")` then customize. Skills teach patterns '
    "and traps; you program the island.\n"
    "- **Check off the plan (HARD):** If this chat has a Plan, tick every step on "
    "it — do not just follow it in your head. Before the work: "
    "`ducky_plan_update_node(node_id, status=\"in_progress\")`. When Done-when is "
    "met: `status=\"completed\"`, then mark the next leaf in_progress. Re-check "
    "the outline (`ducky_get_plan` / Active chat plan block) every tool round. "
    "Mutators are blocked until a leaf is in_progress. Never finish a job with "
    "0 completed steps.\n"
)
